
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox;
	
	private global::Gtk.VBox vbox;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.CheckButton chkLiveControl;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Button btnForward;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Button btnLeft;
	
	private global::Gtk.Button btnReset;
	
	private global::Gtk.Button btnRight;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Fixed fixed3;
	
	private global::Gtk.Button btnBackward;
	
	private global::Gtk.Fixed fixed4;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.VBox vbox26;
	
	private global::Gtk.HBox hbox15;
	
	private global::Gtk.Fixed fixed5;
	
	private global::Gtk.Button btnUp;
	
	private global::Gtk.Fixed fixed6;
	
	private global::Gtk.HBox hbox16;
	
	private global::Gtk.Button btnTurnLeft;
	
	private global::Gtk.Fixed fixed9;
	
	private global::Gtk.Button btnTurnRight;
	
	private global::Gtk.HBox hbox17;
	
	private global::Gtk.Fixed fixed7;
	
	private global::Gtk.Button btnDown;
	
	private global::Gtk.Fixed fixed8;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.VBox vbox12;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.HBox hbox11;
	
	private global::Gtk.VBox vbox13;
	
	private global::Gtk.VBox vbox17;
	
	private global::Gtk.Label lblMoveValue;
	
	private global::Gtk.SpinButton nudMoveValue;
	
	private global::Gtk.VBox vbox21;
	
	private global::Gtk.Label lblBrakeValue;
	
	private global::Gtk.SpinButton nudBrakeValue;
	
	private global::Gtk.VBox vbox14;
	
	private global::Gtk.VBox vbox18;
	
	private global::Gtk.Label lblMoveInterval;
	
	private global::Gtk.SpinButton nudMoveInterval;
	
	private global::Gtk.VBox vbox22;
	
	private global::Gtk.Label lblBrakeInterval;
	
	private global::Gtk.SpinButton nudBrakeInterval;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.VBox vbox15;
	
	private global::Gtk.VBox vbox19;
	
	private global::Gtk.Label lblSmoothValue;
	
	private global::Gtk.SpinButton nudSmoothValue;
	
	private global::Gtk.VBox vbox23;
	
	private global::Gtk.Label lblBrakeSmoothValue;
	
	private global::Gtk.SpinButton nudBrakeSmoothValue;
	
	private global::Gtk.VBox vbox16;
	
	private global::Gtk.VBox vbox20;
	
	private global::Gtk.Label lblSmoothInterval;
	
	private global::Gtk.SpinButton nudSmoothInterval;
	
	private global::Gtk.VBox vbox24;
	
	private global::Gtk.Label lblBrakeSmoothInterval;
	
	private global::Gtk.SpinButton nudBrakeSmoothInterval;
	
	private global::Gtk.Button btnSend;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.NodeView nodeview1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox = new global::Gtk.HBox ();
		this.hbox.Name = "hbox";
		this.hbox.Spacing = 6;
		// Container child hbox.Gtk.Box+BoxChild
		this.vbox = new global::Gtk.VBox ();
		this.vbox.Name = "vbox";
		this.vbox.Spacing = 6;
		// Container child vbox.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.chkLiveControl = new global::Gtk.CheckButton ();
		this.chkLiveControl.Sensitive = false;
		this.chkLiveControl.CanFocus = true;
		this.chkLiveControl.Name = "chkLiveControl";
		this.chkLiveControl.Label = global::Mono.Unix.Catalog.GetString ("Live control");
		this.chkLiveControl.Active = true;
		this.chkLiveControl.DrawIndicator = true;
		this.chkLiveControl.UseUnderline = true;
		this.vbox3.Add (this.chkLiveControl);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.chkLiveControl]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox2.Add (this.fixed1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed1]));
		w2.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnForward = new global::Gtk.Button ();
		this.btnForward.CanFocus = true;
		this.btnForward.Name = "btnForward";
		this.btnForward.UseUnderline = true;
		this.btnForward.Label = global::Mono.Unix.Catalog.GetString ("Forward");
		this.hbox2.Add (this.btnForward);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnForward]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox2.Add (this.fixed2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed2]));
		w4.Position = 2;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox.Add (this.vbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox [this.vbox3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnLeft = new global::Gtk.Button ();
		this.btnLeft.CanFocus = true;
		this.btnLeft.Name = "btnLeft";
		this.btnLeft.UseUnderline = true;
		this.btnLeft.Label = global::Mono.Unix.Catalog.GetString ("Left");
		this.hbox4.Add (this.btnLeft);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnLeft]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnReset = new global::Gtk.Button ();
		this.btnReset.CanFocus = true;
		this.btnReset.Name = "btnReset";
		this.btnReset.UseUnderline = true;
		this.btnReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.hbox4.Add (this.btnReset);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnReset]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnRight = new global::Gtk.Button ();
		this.btnRight.CanFocus = true;
		this.btnRight.Name = "btnRight";
		this.btnRight.UseUnderline = true;
		this.btnRight.Label = global::Mono.Unix.Catalog.GetString ("Right");
		this.hbox4.Add (this.btnRight);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnRight]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox6.Add (this.hbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox6.Add (this.fixed3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed3]));
		w11.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btnBackward = new global::Gtk.Button ();
		this.btnBackward.CanFocus = true;
		this.btnBackward.Name = "btnBackward";
		this.btnBackward.UseUnderline = true;
		this.btnBackward.Label = global::Mono.Unix.Catalog.GetString ("Backward");
		this.hbox6.Add (this.btnBackward);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.btnBackward]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.hbox6.Add (this.fixed4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed4]));
		w13.Position = 2;
		this.vbox6.Add (this.hbox6);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox4.Add (this.vbox6);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox6]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox.Add (this.vbox4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox [this.vbox4]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox26 = new global::Gtk.VBox ();
		this.vbox26.Name = "vbox26";
		this.vbox26.Spacing = 6;
		// Container child vbox26.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox ();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.hbox15.Add (this.fixed5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.fixed5]));
		w17.Position = 0;
		// Container child hbox15.Gtk.Box+BoxChild
		this.btnUp = new global::Gtk.Button ();
		this.btnUp.CanFocus = true;
		this.btnUp.Name = "btnUp";
		this.btnUp.UseUnderline = true;
		this.btnUp.Label = global::Mono.Unix.Catalog.GetString ("Up");
		this.hbox15.Add (this.btnUp);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.btnUp]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.hbox15.Add (this.fixed6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.fixed6]));
		w19.Position = 2;
		this.vbox26.Add (this.hbox15);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox26 [this.hbox15]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox26.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox ();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.btnTurnLeft = new global::Gtk.Button ();
		this.btnTurnLeft.CanFocus = true;
		this.btnTurnLeft.Name = "btnTurnLeft";
		this.btnTurnLeft.UseUnderline = true;
		this.btnTurnLeft.Label = global::Mono.Unix.Catalog.GetString ("Turn left");
		this.hbox16.Add (this.btnTurnLeft);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.btnTurnLeft]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.fixed9 = new global::Gtk.Fixed ();
		this.fixed9.Name = "fixed9";
		this.fixed9.HasWindow = false;
		this.hbox16.Add (this.fixed9);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.fixed9]));
		w22.Position = 1;
		// Container child hbox16.Gtk.Box+BoxChild
		this.btnTurnRight = new global::Gtk.Button ();
		this.btnTurnRight.CanFocus = true;
		this.btnTurnRight.Name = "btnTurnRight";
		this.btnTurnRight.UseUnderline = true;
		this.btnTurnRight.Label = global::Mono.Unix.Catalog.GetString ("Turn right");
		this.hbox16.Add (this.btnTurnRight);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.btnTurnRight]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox26.Add (this.hbox16);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox26 [this.hbox16]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox26.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox ();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.hbox17.Add (this.fixed7);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.fixed7]));
		w25.Position = 0;
		// Container child hbox17.Gtk.Box+BoxChild
		this.btnDown = new global::Gtk.Button ();
		this.btnDown.CanFocus = true;
		this.btnDown.Name = "btnDown";
		this.btnDown.UseUnderline = true;
		this.btnDown.Label = global::Mono.Unix.Catalog.GetString ("Down");
		this.hbox17.Add (this.btnDown);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.btnDown]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.fixed8 = new global::Gtk.Fixed ();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		this.hbox17.Add (this.fixed8);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.fixed8]));
		w27.Position = 2;
		this.vbox26.Add (this.hbox17);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox26 [this.hbox17]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox5.Add (this.vbox26);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox26]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox.Add (this.vbox5);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox [this.vbox5]));
		w30.Position = 2;
		this.hbox.Add (this.vbox);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox [this.vbox]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.vbox17 = new global::Gtk.VBox ();
		this.vbox17.Name = "vbox17";
		this.vbox17.Spacing = 6;
		// Container child vbox17.Gtk.Box+BoxChild
		this.lblMoveValue = new global::Gtk.Label ();
		this.lblMoveValue.Name = "lblMoveValue";
		this.lblMoveValue.LabelProp = global::Mono.Unix.Catalog.GetString ("Move value");
		this.vbox17.Add (this.lblMoveValue);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.lblMoveValue]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox17.Gtk.Box+BoxChild
		this.nudMoveValue = new global::Gtk.SpinButton (0D, 500D, 1D);
		this.nudMoveValue.CanFocus = true;
		this.nudMoveValue.Name = "nudMoveValue";
		this.nudMoveValue.Adjustment.PageIncrement = 10D;
		this.nudMoveValue.ClimbRate = 1D;
		this.nudMoveValue.Numeric = true;
		this.nudMoveValue.Value = 200D;
		this.vbox17.Add (this.nudMoveValue);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.nudMoveValue]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox13.Add (this.vbox17);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox17]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.vbox21 = new global::Gtk.VBox ();
		this.vbox21.Name = "vbox21";
		this.vbox21.Spacing = 6;
		// Container child vbox21.Gtk.Box+BoxChild
		this.lblBrakeValue = new global::Gtk.Label ();
		this.lblBrakeValue.Name = "lblBrakeValue";
		this.lblBrakeValue.LabelProp = global::Mono.Unix.Catalog.GetString ("Brake value");
		this.vbox21.Add (this.lblBrakeValue);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.lblBrakeValue]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vbox21.Gtk.Box+BoxChild
		this.nudBrakeValue = new global::Gtk.SpinButton (0D, 500D, 1D);
		this.nudBrakeValue.CanFocus = true;
		this.nudBrakeValue.Name = "nudBrakeValue";
		this.nudBrakeValue.Adjustment.PageIncrement = 10D;
		this.nudBrakeValue.ClimbRate = 1D;
		this.nudBrakeValue.Numeric = true;
		this.nudBrakeValue.Value = 200D;
		this.vbox21.Add (this.nudBrakeValue);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.nudBrakeValue]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox13.Add (this.vbox21);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox21]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		this.hbox11.Add (this.vbox13);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.vbox13]));
		w38.Position = 0;
		w38.Expand = false;
		w38.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.vbox14 = new global::Gtk.VBox ();
		this.vbox14.Name = "vbox14";
		this.vbox14.Spacing = 6;
		// Container child vbox14.Gtk.Box+BoxChild
		this.vbox18 = new global::Gtk.VBox ();
		this.vbox18.Name = "vbox18";
		this.vbox18.Spacing = 6;
		// Container child vbox18.Gtk.Box+BoxChild
		this.lblMoveInterval = new global::Gtk.Label ();
		this.lblMoveInterval.Name = "lblMoveInterval";
		this.lblMoveInterval.LabelProp = global::Mono.Unix.Catalog.GetString ("Move interval");
		this.vbox18.Add (this.lblMoveInterval);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.lblMoveInterval]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox18.Gtk.Box+BoxChild
		this.nudMoveInterval = new global::Gtk.SpinButton (0D, 10000D, 1D);
		this.nudMoveInterval.CanFocus = true;
		this.nudMoveInterval.Name = "nudMoveInterval";
		this.nudMoveInterval.Adjustment.PageIncrement = 10D;
		this.nudMoveInterval.ClimbRate = 1D;
		this.nudMoveInterval.Numeric = true;
		this.nudMoveInterval.Value = 200D;
		this.vbox18.Add (this.nudMoveInterval);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.nudMoveInterval]));
		w40.Position = 1;
		w40.Expand = false;
		w40.Fill = false;
		this.vbox14.Add (this.vbox18);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.vbox18]));
		w41.Position = 0;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.vbox22 = new global::Gtk.VBox ();
		this.vbox22.Name = "vbox22";
		this.vbox22.Spacing = 6;
		// Container child vbox22.Gtk.Box+BoxChild
		this.lblBrakeInterval = new global::Gtk.Label ();
		this.lblBrakeInterval.Name = "lblBrakeInterval";
		this.lblBrakeInterval.LabelProp = global::Mono.Unix.Catalog.GetString ("Brake interval");
		this.vbox22.Add (this.lblBrakeInterval);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.lblBrakeInterval]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox22.Gtk.Box+BoxChild
		this.nudBrakeInterval = new global::Gtk.SpinButton (0D, 10000D, 1D);
		this.nudBrakeInterval.CanFocus = true;
		this.nudBrakeInterval.Name = "nudBrakeInterval";
		this.nudBrakeInterval.Adjustment.PageIncrement = 10D;
		this.nudBrakeInterval.ClimbRate = 1D;
		this.nudBrakeInterval.Numeric = true;
		this.nudBrakeInterval.Value = 200D;
		this.vbox22.Add (this.nudBrakeInterval);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.nudBrakeInterval]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		this.vbox14.Add (this.vbox22);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.vbox22]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		this.hbox11.Add (this.vbox14);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.vbox14]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		this.hbox9.Add (this.hbox11);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.hbox11]));
		w46.Position = 0;
		w46.Expand = false;
		w46.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.vbox15 = new global::Gtk.VBox ();
		this.vbox15.Name = "vbox15";
		this.vbox15.Spacing = 6;
		// Container child vbox15.Gtk.Box+BoxChild
		this.vbox19 = new global::Gtk.VBox ();
		this.vbox19.Name = "vbox19";
		this.vbox19.Spacing = 6;
		// Container child vbox19.Gtk.Box+BoxChild
		this.lblSmoothValue = new global::Gtk.Label ();
		this.lblSmoothValue.Name = "lblSmoothValue";
		this.lblSmoothValue.LabelProp = global::Mono.Unix.Catalog.GetString ("Smooth value");
		this.vbox19.Add (this.lblSmoothValue);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.lblSmoothValue]));
		w47.Position = 0;
		w47.Expand = false;
		w47.Fill = false;
		// Container child vbox19.Gtk.Box+BoxChild
		this.nudSmoothValue = new global::Gtk.SpinButton (0D, 250D, 1D);
		this.nudSmoothValue.CanFocus = true;
		this.nudSmoothValue.Name = "nudSmoothValue";
		this.nudSmoothValue.Adjustment.PageIncrement = 10D;
		this.nudSmoothValue.ClimbRate = 1D;
		this.nudSmoothValue.Numeric = true;
		this.nudSmoothValue.Value = 10D;
		this.vbox19.Add (this.nudSmoothValue);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.nudSmoothValue]));
		w48.Position = 1;
		w48.Expand = false;
		w48.Fill = false;
		this.vbox15.Add (this.vbox19);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.vbox19]));
		w49.Position = 0;
		w49.Expand = false;
		w49.Fill = false;
		// Container child vbox15.Gtk.Box+BoxChild
		this.vbox23 = new global::Gtk.VBox ();
		this.vbox23.Name = "vbox23";
		this.vbox23.Spacing = 6;
		// Container child vbox23.Gtk.Box+BoxChild
		this.lblBrakeSmoothValue = new global::Gtk.Label ();
		this.lblBrakeSmoothValue.Name = "lblBrakeSmoothValue";
		this.lblBrakeSmoothValue.LabelProp = global::Mono.Unix.Catalog.GetString ("Brake smooth value");
		this.vbox23.Add (this.lblBrakeSmoothValue);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox23 [this.lblBrakeSmoothValue]));
		w50.Position = 0;
		w50.Expand = false;
		w50.Fill = false;
		// Container child vbox23.Gtk.Box+BoxChild
		this.nudBrakeSmoothValue = new global::Gtk.SpinButton (0D, 250D, 1D);
		this.nudBrakeSmoothValue.CanFocus = true;
		this.nudBrakeSmoothValue.Name = "nudBrakeSmoothValue";
		this.nudBrakeSmoothValue.Adjustment.PageIncrement = 10D;
		this.nudBrakeSmoothValue.ClimbRate = 1D;
		this.nudBrakeSmoothValue.Numeric = true;
		this.nudBrakeSmoothValue.Value = 10D;
		this.vbox23.Add (this.nudBrakeSmoothValue);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox23 [this.nudBrakeSmoothValue]));
		w51.Position = 1;
		w51.Expand = false;
		w51.Fill = false;
		this.vbox15.Add (this.vbox23);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.vbox23]));
		w52.Position = 1;
		w52.Expand = false;
		w52.Fill = false;
		this.hbox10.Add (this.vbox15);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox15]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.vbox16 = new global::Gtk.VBox ();
		this.vbox16.Name = "vbox16";
		this.vbox16.Spacing = 6;
		// Container child vbox16.Gtk.Box+BoxChild
		this.vbox20 = new global::Gtk.VBox ();
		this.vbox20.Name = "vbox20";
		this.vbox20.Spacing = 6;
		// Container child vbox20.Gtk.Box+BoxChild
		this.lblSmoothInterval = new global::Gtk.Label ();
		this.lblSmoothInterval.Name = "lblSmoothInterval";
		this.lblSmoothInterval.LabelProp = global::Mono.Unix.Catalog.GetString ("Smooth interval");
		this.vbox20.Add (this.lblSmoothInterval);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.lblSmoothInterval]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		// Container child vbox20.Gtk.Box+BoxChild
		this.nudSmoothInterval = new global::Gtk.SpinButton (0D, 10000D, 1D);
		this.nudSmoothInterval.CanFocus = true;
		this.nudSmoothInterval.Name = "nudSmoothInterval";
		this.nudSmoothInterval.Adjustment.PageIncrement = 10D;
		this.nudSmoothInterval.ClimbRate = 1D;
		this.nudSmoothInterval.Numeric = true;
		this.nudSmoothInterval.Value = 20D;
		this.vbox20.Add (this.nudSmoothInterval);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.nudSmoothInterval]));
		w55.Position = 1;
		w55.Expand = false;
		w55.Fill = false;
		this.vbox16.Add (this.vbox20);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.vbox20]));
		w56.Position = 0;
		w56.Expand = false;
		w56.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.vbox24 = new global::Gtk.VBox ();
		this.vbox24.Name = "vbox24";
		this.vbox24.Spacing = 6;
		// Container child vbox24.Gtk.Box+BoxChild
		this.lblBrakeSmoothInterval = new global::Gtk.Label ();
		this.lblBrakeSmoothInterval.Name = "lblBrakeSmoothInterval";
		this.lblBrakeSmoothInterval.LabelProp = global::Mono.Unix.Catalog.GetString ("Brake smooth interval");
		this.vbox24.Add (this.lblBrakeSmoothInterval);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox24 [this.lblBrakeSmoothInterval]));
		w57.Position = 0;
		w57.Expand = false;
		w57.Fill = false;
		// Container child vbox24.Gtk.Box+BoxChild
		this.nudBrakeSmoothInterval = new global::Gtk.SpinButton (0D, 10000D, 1D);
		this.nudBrakeSmoothInterval.CanFocus = true;
		this.nudBrakeSmoothInterval.Name = "nudBrakeSmoothInterval";
		this.nudBrakeSmoothInterval.Adjustment.PageIncrement = 10D;
		this.nudBrakeSmoothInterval.ClimbRate = 1D;
		this.nudBrakeSmoothInterval.Numeric = true;
		this.vbox24.Add (this.nudBrakeSmoothInterval);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox24 [this.nudBrakeSmoothInterval]));
		w58.Position = 1;
		w58.Expand = false;
		w58.Fill = false;
		this.vbox16.Add (this.vbox24);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.vbox24]));
		w59.Position = 1;
		w59.Expand = false;
		w59.Fill = false;
		this.hbox10.Add (this.vbox16);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox16]));
		w60.Position = 1;
		w60.Expand = false;
		w60.Fill = false;
		this.hbox9.Add (this.hbox10);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.hbox10]));
		w61.Position = 1;
		w61.Expand = false;
		w61.Fill = false;
		this.vbox12.Add (this.hbox9);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox9]));
		w62.Position = 0;
		w62.Expand = false;
		w62.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.btnSend = new global::Gtk.Button ();
		this.btnSend.CanFocus = true;
		this.btnSend.Name = "btnSend";
		this.btnSend.UseUnderline = true;
		this.btnSend.Label = global::Mono.Unix.Catalog.GetString ("Send");
		this.vbox12.Add (this.btnSend);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.btnSend]));
		w63.Position = 1;
		w63.Expand = false;
		w63.Fill = false;
		this.hbox5.Add (this.vbox12);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox12]));
		w64.Position = 0;
		w64.Expand = false;
		w64.Fill = false;
		this.hbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox5]));
		w65.Position = 0;
		w65.Expand = false;
		w65.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w66.Position = 0;
		w66.Expand = false;
		w66.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView ();
		this.nodeview1.Sensitive = false;
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow.Add (this.nodeview1);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w68.Position = 1;
		this.hbox.Add (this.vbox2);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox [this.vbox2]));
		w69.Position = 1;
		w69.Expand = false;
		w69.Fill = false;
		this.Add (this.hbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 714;
		this.DefaultHeight = 361;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnForward.Clicked += new global::System.EventHandler (this.OnBtnForwardClicked);
		this.btnLeft.Clicked += new global::System.EventHandler (this.OnBtnLeftClicked);
		this.btnReset.Clicked += new global::System.EventHandler (this.OnBtnResetClicked);
		this.btnRight.Clicked += new global::System.EventHandler (this.OnBtnRightClicked);
		this.btnBackward.Clicked += new global::System.EventHandler (this.OnBtnBackwardClicked);
		this.btnUp.Clicked += new global::System.EventHandler (this.OnBtnUpClicked);
		this.btnTurnLeft.Clicked += new global::System.EventHandler (this.OnBtnTurnLeftClicked);
		this.btnTurnRight.Clicked += new global::System.EventHandler (this.OnBtnTurnRightClicked);
		this.btnDown.Clicked += new global::System.EventHandler (this.OnBtnDownClicked);
		this.btnSend.Clicked += new global::System.EventHandler (this.OnBtnSendClicked);
	}
}
